#!/bin/sh
# Name : ScanPro
# Date : May 2022
# Description : ScanPro is a ScanPro Scan scripts for hacker's.
# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[1;36m"
cafe="\033[1;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
orange="\033[38;5;122m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
# |
PromptFun(){
  echo ""
  echo "  ${orange}  ┌──[${CYAN}Anlominus${purple}👽${red}Scan${BLUE}Pro$~${orange}]${cyan}"
  echo "  ${orange}  └──╼${green}"
  read s0m3th1ng
}

echo " Enter Target Web/Host/IP: "
read IP_TARGET; clear
echo "\n [#] Your Target : $IP_TARGET"
echo "\n [#] Starting Scanning \n"

# Nmap Target Selection
echo ""
echo " Nmap Target Selection"
echo " [1] Scan a single IP	nmap 192.168.1.1"
echo " [2] Scan a host	nmap www.testhostname.com"
echo " [3] Scan a range of IPs	nmap 192.168.1.1-20"
echo " [4] Scan a subnet	nmap 192.168.1.0/24"
echo " [5] Scan targets from a text file	nmap -iL list-of-ips.txt"
echo ""

# Nmap Port Selection
echo ""
echo " [#] Nmap Port Selection"
echo " [1] Scan a single Port	nmap -p 22 192.168.1.1"
echo " [2] Scan a range of ports	nmap -p 1-100 192.168.1.1"
echo " [3] Scan 100 most common ports (Fast)	nmap -F 192.168.1.1"
echo " [4] Scan all 65535 ports	nmap -p- 192.168.1.1"
echo ""

# Nmap Port Scan types
echo ""
echo " [#] Nmap Port Scan types"
echo " [1] Scan using TCP connect	nmap -sT 192.168.1.1"
echo " [2] Scan using TCP SYN scan (default)	nmap -sS 192.168.1.1"
echo " [3] Scan UDP ports	nmap -sU -p 123,161,162 192.168.1.1"
echo " [4] Scan selected ports - ignore discovery	nmap -Pn -F 192.168.1.1"
echo ""
