#!/bin/sh
# Name : ScanPro
# Date : May 2022
#
# |
red="\033[1;31m"
yellow="\033[33m"
green="\033[32m"
cafe="\033[1;33m"
purple="\033[0;35m"
cyan="\033[38;5;122m"
BLUE="$(printf '\033[36m')"
MAGENTA="$(printf '\033[35m')"
# |
PromptFun(){
  echo ""
  echo "  ${cyan}  ┌──[${BLUE}Anlominus${purple}👽${cafe}Scan${BLUE}Pro$~${cyan}]"
  echo "    |${orange}"
  # echo "  ${orange}  └──╼${green}"
}
prompt="$(PromptFun)"
# |
fun(){
# while-menu: a menu-driven system information program
DELAY=1 # Number of seconds to display results

while true; do
  clear
echo "${cafe} [!]  Please Select:"
echo "${green}       1. Target Selection"
echo "${green}       2. Port Selection"
echo "${green}       3. Scan Types"
echo "${green}       4. Service and Operating System Detection"
echo "${green}       5. Output formats"
echo "${green}       6. NSE Scripting"
echo "${green}       7. HTTP info gathering"
echo "${green}       0. Quit"

echo "${prompt}"
  read -p "    └──╼ Enter selection [0-7] > "
  if [[ $REPLY =~ ^[0-7]$ ]]; then
    case $REPLY in
      1)
      echo "Hostname: $HOSTNAME"
      uptime
      sleep $DELAY
      continue
      ;;
      2)
      df -h
      sleep $DELAY
      continue
      ;;
      3)
      if [[ $(id -u) -eq 0 ]]; then
        echo "Home Space Utilization (All Users)"
        du -sh /home/* 2> /dev/null
      else
        echo "Home Space Utilization ($USER)"
        du -sh $HOME 2> /dev/null
      fi
      sleep $DELAY
      continue
      ;;
      0)
      break
      ;;
    esac
  else
    echo "Invalid entry."
    sleep $DELAY
  fi
done
echo "Program terminated."
}
fun
